package com.mandatoryfun.ultramegafactory;

import com.mandatoryfun.ultramegafactory.handler.TooltipHandler;
import com.mandatoryfun.ultramegafactory.lib.RefStrings;
import com.mandatoryfun.ultramegafactory.proxy.CommonProxy;
import net.minecraft.util.text.TextFormatting;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = RefStrings.MODID, version = RefStrings.VERSION, name = RefStrings.NAME, guiFactory = RefStrings.GUI_FACTORY_CLASS)
public class Core {

    @SidedProxy(clientSide = RefStrings.CLIENTSIDE, serverSide = RefStrings.SERVERSIDE, modId = RefStrings.MODID)
    public static CommonProxy proxy;

    @Mod.Instance
    public static Core instance = new Core();

    @EventHandler
    public void preInit(FMLPreInitializationEvent e) {
        System.out.println("PREINIT for " + RefStrings.NAME);
        proxy.preInit(e);
        // create and register blocks and item
        e.getModMetadata().autogenerated = false;
        e.getModMetadata().credits = TextFormatting.BLUE + "Cendrb, WesterWest";
        e.getModMetadata().authorList.add(TextFormatting.RED + "Cendrb, WesterWest");
        e.getModMetadata().description = TextFormatting.YELLOW + "Add your description here";
        e.getModMetadata().url = "https://github.com/Cendrb/UltraMegaFactory";
        e.getModMetadata().logoFile = "assets/ultramegafactory/textures/logo/logo.png";
        e.getModMetadata().version = RefStrings.VERSION;
    }

    @EventHandler
    public void init(FMLInitializationEvent e) {
        proxy.init(e);
        System.out.println("INIT for " + RefStrings.NAME);
        // crafting recipes, new handlers
    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent e) {
        proxy.postInit(e);
        System.out.println("POSTINIT for " + RefStrings.NAME);
        // communicate with other mods
    }
}
